name: Update Cotec-JSON

# トリガー
on: 
    schedule:
        - cron: '0 0 2 * *' # 毎月2日

    # 手動実行用
    workflow_dispatch:

jobs:
    update-cotec-json:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: 22

            # 依存関係のインストール
            - name: Install dependencies
              run: npm install

            # 実行
            - name: Run tsx
              run: npm run tsx

            # コミット (actions-user)
            - name: Commit
              run: |
                git config user.name "actions-user"
                git config user.email "action@github.com"
                git add .
                git commit --allow-empty -m "updated Cotec-JSON"
                git push

            
        


